# main window
MAIN_WINDOW_WIDTH = 1000
MAIN_WINDOW_HEIGHT = 500

# code editor
CODE_WINDOW_WIDTH = 600
CODE_WINDOW_HEIGHT = 500
CODE_TEXT_LINE_LENGTH = 120
CODE_LINE_TEXT_WIDTH = 3 # as going up to 256 lines
MAX_CODE_LINES = 256

# log window
LOG_WINDOW_WIDTH = 800
LOG_WINDOW_HEIGHT = 200

# pinout window
PINOUT_WINDOW_WIDTH = 300
PINOUT_WINDOW_HEIGHT = 300

# MCU constants
PROGRAM_MEMORY_SIZE = 512  # x 14-bit instructions (13-bit addressing allows up to 8192 program memory spaces)
DATA_MEMORY_SIZE = 256 # bytes

PROG_MEMORY_WINDOW_WIDTH = 215
PROG_MEMORY_WINDOW_HEIGHT = 170

DATA_MEMORY_WINDOW_WIDTH = 263
DATA_MEMORY_WINDOW_HEIGHT = 170

STACK_SIZE = 8

# display style constants
COLOUR_PRIMARY = "#99ccff"
COLOUR_SECONDARY = "#33ccf"
COLOUR_MAIN_BACKGROUND = "#666666"
COLOUR_INNER_BACKGROUND = "#8c8c8c"
COLOUR_INNER2_BACKGROUND = "#b3b3b3"
COLOUR_LIGHT_BACKGROUND = "#e6e6e6"
COLOUR_MEMORY_LABEL_BACKGROUND = "#ffffff"
COLOUR_MEMORY_FRAME_BACKGROUND = "#cccccc"
COLOUR_DARK_BACKGROUND = "#262626"
COLOUR_LIGHT_TEXT = "#b3b3b3"
COLOUR_DARK_TEXT = "#0d0d0d"

LOG_BACKGROUND_DARK = "#333333"
LOG_BACKGROUND_LIGHT = "#f2f2f2"

CODE_BACKGROUND_DARK = "#333333"
CODE_BACKGROUND_LIGHT = "#f2f2f2"
CODE_LIGHT_TEXT = "#999999"
CODE_DARK_TEXT = "#737373"

COLOUR_BUTTON_NORMAL = "#80ccff"
COLOUR_BUTTON_ACTIVE = "#ccebff"
COLOUR_BUTTON_PRESSED = "#33adff"

COLOUR_BUTTON_NORMAL_2 = "#ff6666"
COLOUR_BUTTON_ACTIVE_2 = "#ff9999"
COLOUR_BUTTON_PRESSED_2 = "#ff1a1a"

COLOUR_BUTTON_NORMAL_3 = "#adebad"
COLOUR_BUTTON_ACTIVE_3 = "#d6f5d6"
COLOUR_BUTTON_PRESSED_3 = "#46d246"

COLOUR_BUTTON_NORMAL_4 = "#ffb366"
COLOUR_BUTTON_ACTIVE_4 = "#ffd9b3"
COLOUR_BUTTON_PRESSED_4 = "#ff8c1a"

COLOUR_PINOUT_BUTTON_ON = "#80ff80"
COLOUR_PINOUT_BUTTON_OFF = "#ffffff"
COLOUR_PINOUT_BUTTON_ACTIVE = "#b3ffb3"
COLOUR_PINOUT_BUTTON_PRESSED = "#00cc00"

CHECKBOX_TICK ="#006622"
PROGRAM_MEMORY_HIGHLIGHT = "#ffb3b3"
DATA_MEMORY_HIGHLIGHT = "#00cc00"
PCL_PCLATH_HIGHLIGHT = "#d6f5d6"
BIT_HIGHLIGHT = "#ffbf80"
STACK_HIGHLIGHT = "#ffccff"
VISITED_DATA_ADDRESS = "#d9d9d9"
