# main window
MAIN_WINDOW_WIDTH = 700
MAIN_WINDOW_HEIGHT = 600

# code editor
CODE_WINDOW_WIDTH = 400
CODE_EDITOR_WIDTH = 100
CODE_LINE_TEXT_WIDTH = 3 # as going up to 256 lines
MAX_CODE_LINES = 256

# log window
LOG_WINDOW_HEIGHT = 200

# MCU constants
PROGRAM_MEMORY_SIZE = 512  # x 14-bit instructions (13-bit addressing allows up to 8192 program memory spaces)
DATA_MEMORY_SIZE = 256 # bytes

PROG_MEMORY_WINDOW_WIDTH = 215
PROG_MEMORY_WINDOW_HEIGHT = 260

DATA_MEMORY_WINDOW_WIDTH = 263
DATA_MEMORY_WINDOW_HEIGHT = 260

STACK_SIZE = 8

# 'file addresses' constants for highlighting
NONE = -1

# display style constants
COLOUR_PRIMARY = "#99ccff"
COLOUR_SECONDARY = "#33ccf"
COLOUR_MAIN_BACKGROUND = "#666666"
COLOUR_INNER_BACKGROUND = "#a6a6a6"
COLOUR_INNER2_BACKGROUND = "#bfbfbf"
COLOUR_LIGHT_BACKGROUND = "#e6e6e6"
COLOUR_MEMORY_LABEL_BACKGROUND = "#ffffff"
COLOUR_MEMORY_FRAME_BACKGROUND = "#cccccc"
COLOUR_DARK_BACKGROUND = "#262626"
COLOUR_LIGHT_TEXT = "#b3b3b3"
COLOUR_DARK_TEXT = "#0d0d0d"

COLOUR_BUTTON_NORMAL = "#99d6ff"
COLOUR_BUTTON_ACTIVE = "#ccebff"
COLOUR_BUTTON_PRESSED = "#80ccff"

COLOUR_BUTTON_NORMAL_2 = "#ff9999"
COLOUR_BUTTON_ACTIVE_2 = "#ffcccc"
COLOUR_BUTTON_PRESSED_2 = "#ff3333"

PROGRAM_MEMORY_HIGHLIGHT = "#ffb3b3"
DATA_MEMORY_HIGHLIGHT = "#00cc00"
PCL_PCLATH_HIGHLIGHT = "#d6f5d6"
BIT_HIGHLIGHT = "#ffbf80"
STACK_HIGHLIGHT = "#ffccff"
VISITED_DATA_ADDRESS = "#e6e6e6"